### ISSUE TITLE
Division by zero in metrics module

### ISSUE THREAD

**Issue by qarawlus** [RealVNF/coordination-simulation#102]
When running the RL agent, I get division by zero error in the metrics module when using simulator run durations under 50. 

This is a new bug that came to be after #101. 

Traced issue back to `run_generated_flows` https://github.com/RealVNF/coordination-simulation/blob/89c0a489f9728e1d5b9f785d0d9344fa5a3ea6ee/src/coordsim/metrics/metrics.py#L140.

**Comment by qarawlus** [comment]
@stefanbschneider, The error is in averaging the path delay over the number of generated flows every time a path delay happens. I thought the average path delay is the total delay divided over all number of path delays. For now I will just move to the the end of the metrics module so that we don't get the division by zero error.

**Comment by stefanbschneider** [comment]
I wanted to have the average path delay per flow per run, which is what the agent can influence to reduce the total e2e delay. To approximate that, I took the total path delay in the run and divided by number of flows. I originally took the number of processed flows `run_processed_flows`, but then switched to the generated flows `run_generated_flows`. But forgot to adjust the if condition: https://github.com/RealVNF/coordination-simulation/blob/89c0a489f9728e1d5b9f785d0d9344fa5a3ea6ee/src/coordsim/metrics/metrics.py#L139

**Comment by stefanbschneider** [comment]
Our "normal" overall avg path delay averages over `num_path_delays`: https://github.com/RealVNF/coordination-simulation/blob/89c0a489f9728e1d5b9f785d0d9344fa5a3ea6ee/src/coordsim/metrics/metrics.py#L161

This doesn't tell us directly if an agent crossed many paths because it only refers to a single path between two VNFs.

Maybe a better name for my new metric would be something like `run_avg_flow_path_delay` since I want to have the total path delay per flow per run on average.
